apiVersion: apps/v1
kind: Deployment
metadata:
  name: error-generator-deployment
  labels:
    app: error-generator
spec:
  replicas: 3
  selector:
    matchLabels:
      app: error-generator
  template:
    metadata:
      labels:
        app: error-generator
    spec:
      containers:
        - name: error-generator
          image: sdrshnrcks/error-generator:1.0
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: error-generator-service
spec:
  selector:
    app: error-generator
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080